version: '3.9'
services:
  web:
    build: .
    command: ["gunicorn", "--bind", ":8000", "backend.wsgi:application"]
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
      - redis

    networks:
      - webnet-network

  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - webnet-network


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - webnet-network



  daphne:
    build: .
    command: daphne -b 0.0.0.0 -p 8001 backend.asgi:application
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
    - DJANGO_SETTINGS_MODULE=backend.settings
    networks:
      - webnet-network

volumes:
  pg_data:

networks:
  webnet-network:
    driver: bridge