# Generated by Django 5.1 on 2024-08-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_time', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='thread_name',
            field=models.CharField(max_length=255),
        ),
    ]
